### ISSUE TITLE
Invoke-AzureStorageBlobUploadFinalize, missing Content-Type header

### ISSUE THREAD

**Issue by CatalinTRSK** [MSEndpointMgr/IntuneWin32App#155]
Hello, can you please `add` this headers to the Invoke-AzureStorageBlobUploadFinalize function?

```
 $headers = @{"Content-Type" = "text/plain; charset=UTF-8"}
 $WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Body $XML -Headers $headers -ErrorAction Stop
```

**Comment by jyonke** [comment]
This appears to be related to PowerShell Core version 7.4.2. If I downgrade to 7.4.1, I no longer see this issue. 


![Screenshot 2024-04-16 111054](https://github.com/MSEndpointMgr/IntuneWin32App/assets/19600775/b1269389-0bab-4cf2-92d6-0accafa78031)

**Comment by LeeParWal** [comment]
Just adding a quick note - we've seen early promising signs testing this on our parallel project where we similarly didn't have the header declared on the finalize call and ran into 7.4.2 when it landed on the AZDO agents yesterday.

**Comment by lsalle** [comment]
I can confirm that IntuneWin32App.Add-IntuneWin32App fails with Powershell 7.4.2.

Console output include the messages:

"
WARNING: Failed to finalize Azure Storage blob upload. Error message: The given key 'Content-Type' was not present in the dictionary.
WARNING: Intune service request for operation 'CommitFile' failed
WARNING: Failed to create Win32 app, commit file request operation failed
"

The issue could be circumvented by using Windows Powershell 5.1.

**Comment by RutgerP** [comment]
I'm also getting the error on file Invoke-AzureStorageBlobUploadChunk.ps1.
Anyone has a solution for this or should I go back to Powershell 5.1?

![image](https://github.com/MSEndpointMgr/IntuneWin32App/assets/27196553/27c14c40-fa13-41fe-946b-365101be3dd7)
![image](https://github.com/MSEndpointMgr/IntuneWin32App/assets/27196553/ffc67db5-f216-4405-9a72-b11467adc985)

**Comment by jaspain** [comment]
I ran into this same problem today with PowerShell 7.4.2 and Micrsosft.Graph 2.19.0. \IntuneWin32App\1.4.4\Private\Invoke-AzureStorageBlobUploadFinalize.ps1 threw the warnings:
```
WARNING: Failed to finalize Azure Storage blob upload. Error message: The given key 'Content-Type' was not present in the dictionary.
WARNING: Intune service request for operation 'CommitFile' failed
WARNING: Failed to create Win32 app, commit file request operation failed
```

To fix this, starting in line 35, change:
```
$XML += '</BlockList>'

try {
    $WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Body $XML -ErrorAction Stop
}
```
to
```
$XML += '</BlockList>'

$Headers = @{
    "content-type" = "text/plain; charset=iso-8859-1"
}
try {
    $WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Headers $Headers -Body $XML -ErrorAction Stop
}
```
See also [Add-IntuneWin32App.ps1 'CommitFile' failed error with PowerShell 7.4.0 #128](https://github.com/MSEndpointMgr/IntuneWin32App/issues/128), where the same problem occurred in AzureStorageBlobUploadChunk.ps1.

**Comment by RutgerP** [comment]
> I ran into this same problem today with PowerShell 7.4.2 and Micrsosft.Graph 2.19.0. \IntuneWin32App\1.4.4\Private\Invoke-AzureStorageBlobUploadFinalize.ps1 threw the warnings:
> 
> ```
> WARNING: Failed to finalize Azure Storage blob upload. Error message: The given key 'Content-Type' was not present in the dictionary.
> WARNING: Intune service request for operation 'CommitFile' failed
> WARNING: Failed to create Win32 app, commit file request operation failed
> ```
> 
> To fix this, starting in line 35, change:
> 
> ```
> $XML += '</BlockList>'
> 
> try {
>     $WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Body $XML -ErrorAction Stop
> }
> ```
> 
> to
> 
> ```
> $XML += '</BlockList>'
> 
> $Headers = @{
>     "content-type" = "text/plain; charset=iso-8859-1"
> }
> try {
>     $WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Headers $Headers -Body $XML -ErrorAction Stop
> }
> ```
> 
> See also [Add-IntuneWin32App.ps1 'CommitFile' failed error with PowerShell 7.4.0 #128](https://github.com/MSEndpointMgr/IntuneWin32App/issues/128), where the same problem occurred in AzureStorageBlobUploadChunk.ps1.

Thanks got it running again!

**Comment by rdoloto-nps** [comment]
going to close other issue. making those  changes as per thread fixed.
7.4.2 powershell

**Comment by aollivierre** [comment]
Please update the function the following for to fix the issue with PS 7.4.2. FYI Handle-Error is a custom function that I built wrapping out Get-Error (VERY USEFUL in PS7)

The error message indicates that the 'Content-Type' key is not present in the dictionary when making the Invoke-RestMethod call. This suggests that the Content-Type header is required for the request but is missing.

By explicitly setting the Content-Type header to application/xml, the Invoke-RestMethod call should properly handle the request. This should resolve the KeyNotFoundException error you encountered.

You can add the Content-Type header explicitly to the Invoke-RestMethod call. Here's the modified function:

\IntuneWin32App\1.4.4\Private\Invoke-AzureStorageBlobUploadFinalize.ps1

function Invoke-AzureStorageBlobUploadFinalize {
    <#
    .SYNOPSIS
        Finalize upload of chunks of the .intunewin file into Azure Storage blob container.

    .DESCRIPTION
        Finalize upload of chunks of the .intunewin file into Azure Storage blob container.

        This is a modified function that was originally developed by Dave Falkus and is available here:
        https://github.com/microsoftgraph/powershell-intune-samples/blob/master/LOB_Application/Win32_Application_Add.ps1        

    .NOTES
        Author:      Nickolaj Andersen
        Contact:     @NickolajA
        Created:     2020-01-04
        Updated:     2020-01-04

        Version history:
        1.0.0 - (2020-01-04) Function created
    #>    
    param(
        [parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$StorageUri,

        [parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [System.Object]$ChunkID
    )
    $Uri = "$($StorageUri)&comp=blocklist"
	$XML = '<?xml version="1.0" encoding="utf-8"?><BlockList>'
	foreach ($Chunk in $ChunkID) {
		$XML += "<Latest>$($Chunk)</Latest>"
	}
	$XML += '</BlockList>'

	try {
        $Headers = @{
            "Content-Type" = "application/xml"
        }
		$WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Body $XML -Headers $Headers -ErrorAction Stop
	}
	catch {
		# Write-EnhancedLog -Message "Failed to finalize Azure Storage blob upload. Error message: $($_.Exception.Message)"

        Handle-Error -ErrorRecord $_
	}
}

**Comment by Soolkiki** [comment]
We can confirm we're have this issue on version 7.4.3 as well. 
![image](https://github.com/MSEndpointMgr/IntuneWin32App/assets/17281121/c1ceecc4-c043-458a-be45-91fd4bd1ca67)

We don't have a good way to overload the Content-Type since we're running this in a Github Runner. Is this still an issue you're reviewing?

**Comment by k0space** [comment]
Having this issue as well. 
![CreatingIntuneAppConfigProfFailure](https://github.com/MSEndpointMgr/IntuneWin32App/assets/171349775/6b524a2a-3655-43e2-be14-2acb2744ea8c)
Works on PowerShell 5.1, but because this is in a pipeline we cannot explicitly set the Content-Type header as suggested.

**Comment by PckgrTom** [comment]
> Please update the function Invoke-AzureStorageBlobUploadFinalize to fix the issue with PS 7.4.2. FYI Handle-Error is a custom function that I built wrapping out Get-Error (VERY USEFUL in PS7)
> 
> The error message indicates that the 'Content-Type' key is not present in the dictionary when making the Invoke-RestMethod call. This suggests that the Content-Type header is required for the request but is missing.
> 
> By explicitly setting the Content-Type header to application/xml, the Invoke-RestMethod call should properly handle the request. This should resolve the KeyNotFoundException error you encountered.
> 
> You can add the Content-Type header explicitly to the Invoke-RestMethod call. Here's the modified function:
> 
> \IntuneWin32App\1.4.4\Private\Invoke-AzureStorageBlobUploadFinalize.ps1
> 
> ```
> function Invoke-AzureStorageBlobUploadFinalize {
>     <#
>     .SYNOPSIS
>         Finalize upload of chunks of the .intunewin file into Azure Storage blob container.
> 
>     .DESCRIPTION
>         Finalize upload of chunks of the .intunewin file into Azure Storage blob container.
> 
>         This is a modified function that was originally developed by Dave Falkus and is available here:
>         https://github.com/microsoftgraph/powershell-intune-samples/blob/master/LOB_Application/Win32_Application_Add.ps1        
> 
>     .NOTES
>         Author:      Nickolaj Andersen
>         Contact:     @NickolajA
>         Created:     2020-01-04
>         Updated:     2020-01-04
> 
>         Version history:
>         1.0.0 - (2020-01-04) Function created
>     #>    
>     param(
>         [parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [string]$StorageUri,
> 
>         [parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [System.Object]$ChunkID
>     )
>     $Uri = "$($StorageUri)&comp=blocklist"
> 	$XML = '<?xml version="1.0" encoding="utf-8"?><BlockList>'
> 	foreach ($Chunk in $ChunkID) {
> 		$XML += "<Latest>$($Chunk)</Latest>"
> 	}
> 	$XML += '</BlockList>'
> 
> 	try {
>         $Headers = @{
>             "Content-Type" = "application/xml"
>         }
> 		$WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Body $XML -Headers $Headers -ErrorAction Stop
> 	}
> 	catch {
> 		# Write-EnhancedLog -Message "Failed to finalize Azure Storage blob upload. Error message: $($_.Exception.Message)"
> 
>         Handle-Error -ErrorRecord $_
> 	}
> }
> ```

Thanks for this fix mate!

**Comment by SunsparcSolaris** [comment]
I am on Powershell 7.4.4 and IntuneWin32App module version 1.4.4 yet still encountering this issue. I have made the necessary changes to the files, they appear identically to the fix examples posted earlier in this thread.

> WARNING: Failed to finalize Azure Storage blob upload. Error message: The given key 'Content-Type' was not present in the dictionary.
> WARNING: Intune service request for operation 'CommitFile' failed
> WARNING: Failed to create Win32 app, commit file request operation failed

Invoke-AzureStorageBlobUploadFinalize.ps1, starting line 35

```
$XML += '</BlockList>'

	try {
        $Headers = @{
            "Content-Type" = "application/xml"
        }
		$WebResponse = Invoke-RestMethod -Uri $Uri -Method "Put" -Body $XML -Headers $Headers -ErrorAction Stop
	}
```
I also tried adding ```-ContentType "application.xml"``` to the ```Invoke-RestMethod``` command in the file to no avail.

**Comment by obuolinis** [comment]
> I am on Powershell 7.4.4 and IntuneWin32App module version 1.4.4 yet still encountering this issue. I have made the necessary changes to the files, they appear identically to the fix examples posted earlier in this thread.

Just tested the fix from https://github.com/MSEndpointMgr/IntuneWin32App/pull/157 with PS 7.4.4 and can confirm it does the job.
It's just unfortunate that Nickolaj can't find time to merge it.
